// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFlVz1rOmAbh0OHG7cLTDetXfXflWwqng',
    appId: '1:85527151375:web:c6091bf3f5e96cb3cab47a',
    messagingSenderId: '85527151375',
    projectId: 'ecommerceapp-cde9f',
    authDomain: 'ecommerceapp-cde9f.firebaseapp.com',
    storageBucket: 'ecommerceapp-cde9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSDlPjmiAOYj9emoo92Q-n-kzmQucwin4',
    appId: '1:85527151375:android:ba808fd7f59dafc9cab47a',
    messagingSenderId: '85527151375',
    projectId: 'ecommerceapp-cde9f',
    storageBucket: 'ecommerceapp-cde9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Erd-MmqlYynCcsRfVOeoBOizjWzTdWo',
    appId: '1:85527151375:ios:890f7185261d0cebcab47a',
    messagingSenderId: '85527151375',
    projectId: 'ecommerceapp-cde9f',
    storageBucket: 'ecommerceapp-cde9f.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Erd-MmqlYynCcsRfVOeoBOizjWzTdWo',
    appId: '1:85527151375:ios:6c041d04b9bac8b5cab47a',
    messagingSenderId: '85527151375',
    projectId: 'ecommerceapp-cde9f',
    storageBucket: 'ecommerceapp-cde9f.appspot.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
